# Generated by Django 4.1.4 on 2022-12-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('johnapp', '0004_pool_fname_pool_lname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='fname',
            field=models.CharField(blank=True, max_length=100, verbose_name='fname'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='interest',
            field=models.CharField(max_length=100, verbose_name='interest'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='lname',
            field=models.CharField(blank=True, max_length=100, verbose_name='lname'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='location',
            field=models.CharField(max_length=100, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='occupation',
            field=models.CharField(max_length=100, verbose_name='occupation'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='pnumber',
            field=models.BigIntegerField(verbose_name='pnumber'),
        ),
    ]
