# Generated by Django 4.1.4 on 2022-12-16 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('johnapp', '0006_alter_pool_email_alter_pool_pnumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pool',
        ),
    ]
