# Generated by Django 4.1.4 on 2022-12-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('johnapp', '0007_delete_pool'),
    ]

    operations = [
        migrations.CreateModel(
            name='pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('fname', models.CharField(blank=True, max_length=100, verbose_name='fname')),
                ('lname', models.CharField(blank=True, max_length=100, verbose_name='lname')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('occupation', models.CharField(max_length=100, verbose_name='occupation')),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('pnumber', models.CharField(max_length=100, verbose_name='pnumber')),
                ('interest', models.CharField(max_length=100, verbose_name='interest')),
            ],
        ),
    ]
